### ISSUE TITLE
启动时报错无法加载插件

### ISSUE THREAD

**Issue by Rcrafte22** [pcrbot/vtb-bili#6]
报错信息如下

[2021-12-05 11:54:36,319 nonebot] ERROR: Failed to import "hoshino.modules.vtb-bili.vtb_subscriptions_query", error: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/vtb-bili/bilibili_vtbs.json'
[2021-12-05 11:54:36,319 nonebot] ERROR: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/vtb-bili/bilibili_vtbs.json'
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/HoshinoBot/hoshino/modules/vtb-bili/vtb_subscriptions_query.py", line 19, in <module>
    load_vtb()  #hoshino在启动时就会自动运行一遍写在外面的函数，不太需要@on_startup
  File "/root/HoshinoBot/hoshino/modules/vtb-bili/vtb_subscriptions_query.py", line 16, in load_vtb
    with open(os.path.join(os.path.dirname(__file__), 'bilibili_vtbs.json'), "r", encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/vtb-bili/bilibili_vtbs.json'

**Comment by kosakarin** [comment]
你这个报错是缺少文件了，你确认下文件路径什么的对不对

**Comment by kosakarin** [comment]
我看了下源码，上次我pullrequest之后忘记改路径和上传一份这个json文件了，你在这个插件的同目录下创建一个bilibili_vtbs.json这个json文件，然后把路径修改下就可以了，我的锅 回头我重新pull一下

**Comment by kosakarin** [comment]
好了 我现在修复好了，如果你还没有解决的话可以直接重新下载一份最新的源码，如果原作者还没有通过我的pullrequest的话你可以先去我的分支下面下载

**Comment by Rcrafte22** [comment]
好的，辛苦了
